repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test

  - repo: https://github.com/python-poetry/poetry
    rev: '{{ cookiecutter.poetry_version }}'
    hooks:
    -   id: poetry-check

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python{{ cookiecutter.python_version }}

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
{% if cookiecutter.use_pre_commit_ci %}
ci:
    autofix_prs: true
    autoupdate_schedule: weekly
    submodules: false
{% endif %}
